# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8001
  connection-timeout: 5000ms
  servlet:
    context-path: /forestage

spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  redis:
    open: true  # 是否开启redis缓存  true开启   false关闭
    database: 0
    host: xxxx  # redis地址
    port: xxxx        # redis端口
    password: xxxx   # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 100  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 5      # 连接池中的最大空闲连接
        min-idle: 2       # 连接池中的最小空闲连接
  mvc:
    throw-exception-if-no-handler-found: true
    #  解决springboot配置@ControllerAdvice不能捕获NoHandlerFoundException问题  参考：https://www.cnblogs.com/wang-yaz/p/13225830.html
  #  resources:
  #    add-mappings: false

  datasource:
#    username: root
#    password: 1234
#    url: jdbc:mysql://106.55.5.78:3306/lost_and_found?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
#    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 30000

#    阿里云OSS信息配置
  cloud:
    alicloud:
      access-key: xxxx
      secret-key: xxxx
      oss:
        endpoint: xxxx
        bucket: xxxx
#     数据源max-lifetime
    datasource:
      hikari:
        max-lifetime: 30000
#     开启debug
logging:
  level:
    cn.bfcod.lost_and_found: debug

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.bfcod.*.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: delStatus
    banner: false
    #刷新mapper 调试神器
    refresh-mapper: true
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'


